collect:
  sqldir: ./tempSQL/
  minimum_cycle: .5

  tags:
    - type: pylogix_counter       # type = counter|value
      processor_ip: 10.4.42.135     # processor_ip is the controller's ip address
      processor_slot: 3             # processor_slot is the controller's slot
      tag: Program:Production.ProductionData.DailyCounts.DailyTotal  # tag is the PLC tag to read
      Part_Type_Tag: Stn010.PartType # tag containing what part type is currently running
      Part_Type_Map:                # map values in above to a string to write in the part type db colum
        '0': 50-4865
        '1': 50-5081
      frequency: .5                 # how often to try to read the tag in seconds
      table: GFxPRoduction          # database table to write to
      Machine: 1617                 # written to machine colum in db
      # used internally to track the readings
      nextread: 0     # timestamp of the next reading
      lastcount: 0    # last counter value
      lastread: 0     # timestamp of the last read
    
post:
  sqldir: ./tempSQL/
  dbconfig:
    database: prodrptdb
    user: stuser
    password: stp383
    host: 10.4.1.224

configure:
  key: value
  key2: value



