1617production: 
  # type = counter|value
  type: pylogix_counter
  # processor_ip is the controller's ip address
  processor_ip: 10.4.42.135
  # processor_slot is the controller's slot
  processor_slot: 3
  # tag is the PLC tag to read
  tag: Program:Production.ProductionData.DailyCounts.DailyTotal
  # tag containing what part type is currently running
  Part_Type_Tag: Stn010.PartType
  # map values in above to a string to write in the part type db colum
  Part_Type_Map: 
    0: 50-4865
    1: 50-5081
  # how often to try to read the tag in seconds
  frequency: .5
  # database table to write to
  table: GFxPRoduction
  # Machine is written into the machine colum in the database table
  Machine: 1617
  # used internally to track the readings
  nextread: 0     # timestamp of the next reading
  lastcount: 0    # last counter value
  lastread: 0     # timestamp of the last read
